/**
 * Error code catalogue (AGENTS.md section 36).
 *
 * The backend emits machine-readable codes; clients branch on `code`, never on
 * `message` text (which may be translated).
 */
export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MALFORMED_JSON: 'MALFORMED_JSON',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  CREDENTIALS_INCOMPLETE: 'CREDENTIALS_INCOMPLETE',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',

  MERCHANT_NOT_FOUND: 'MERCHANT_NOT_FOUND',
  MERCHANT_INVALID_STATE: 'MERCHANT_INVALID_STATE',
  MERCHANT_RUT_CONFLICT: 'MERCHANT_RUT_CONFLICT',

  ORDER_INVALID_STATE: 'ORDER_INVALID_STATE',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_CART_MULTI_MERCHANT: 'ORDER_CART_MULTI_MERCHANT',
  ORDER_EMPTY_CART: 'ORDER_EMPTY_CART',
  ORDER_OUT_OF_STOCK: 'ORDER_OUT_OF_STOCK',
  ORDER_MERCHANT_NOT_SERVICEABLE: 'ORDER_MERCHANT_NOT_SERVICEABLE',
  ORDER_ADDRESS_OUT_OF_ZONE: 'ORDER_ADDRESS_OUT_OF_ZONE',

  DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',
  DELIVERY_CODE_INVALID: 'DELIVERY_CODE_INVALID',
  DELIVERY_CODE_LOCKED: 'DELIVERY_CODE_LOCKED',
  DELIVERY_ALREADY_COMPLETED: 'DELIVERY_ALREADY_COMPLETED',
  DELIVERY_NOT_ASSIGNED_TO_DRIVER: 'DELIVERY_NOT_ASSIGNED_TO_DRIVER',

  DISPATCH_NO_DRIVER_AVAILABLE: 'DISPATCH_NO_DRIVER_AVAILABLE',
  DRIVER_NOT_ELIGIBLE: 'DRIVER_NOT_ELIGIBLE',
  DRIVER_NOT_APPROVED: 'DRIVER_NOT_APPROVED',

  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_INVALID_STATE: 'PAYMENT_INVALID_STATE',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  REFUND_EXCEEDS_PAID_AMOUNT: 'REFUND_EXCEEDS_PAID_AMOUNT',

  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_REQUEST_IN_PROGRESS: 'IDEMPOTENCY_REQUEST_IN_PROGRESS',

  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  STORAGE_ERROR: 'STORAGE_ERROR',

  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** HTTP status mapping per error code, so controllers and filters agree. */
export const ERROR_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = Object.freeze({
  VALIDATION_FAILED: 400,
  MALFORMED_JSON: 400,
  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_SUSPENDED: 403,
  ACCOUNT_DISABLED: 403,
  EMAIL_NOT_VERIFIED: 403,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  TOKEN_REVOKED: 401,
  REFRESH_TOKEN_REUSED: 401,
  ACCOUNT_LOCKED: 429,
  CREDENTIALS_INCOMPLETE: 400,
  EMAIL_ALREADY_REGISTERED: 409,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,

  MERCHANT_NOT_FOUND: 404,
  MERCHANT_INVALID_STATE: 409,
  MERCHANT_RUT_CONFLICT: 409,

  ORDER_INVALID_STATE: 409,
  ORDER_NOT_FOUND: 404,
  ORDER_CART_MULTI_MERCHANT: 409,
  ORDER_EMPTY_CART: 409,
  ORDER_OUT_OF_STOCK: 409,
  ORDER_MERCHANT_NOT_SERVICEABLE: 409,
  ORDER_ADDRESS_OUT_OF_ZONE: 422,

  DELIVERY_NOT_FOUND: 404,
  DELIVERY_CODE_INVALID: 400,
  DELIVERY_CODE_LOCKED: 423,
  DELIVERY_ALREADY_COMPLETED: 409,
  DELIVERY_NOT_ASSIGNED_TO_DRIVER: 403,

  DISPATCH_NO_DRIVER_AVAILABLE: 409,
  DRIVER_NOT_ELIGIBLE: 403,
  DRIVER_NOT_APPROVED: 403,

  PAYMENT_NOT_FOUND: 404,
  PAYMENT_FAILED: 402,
  PAYMENT_INVALID_STATE: 409,
  PAYMENT_SIGNATURE_INVALID: 400,
  REFUND_EXCEEDS_PAID_AMOUNT: 409,

  IDEMPOTENCY_KEY_REQUIRED: 400,
  IDEMPOTENCY_KEY_REUSED: 409,
  IDEMPOTENCY_REQUEST_IN_PROGRESS: 409,

  UPLOAD_INVALID_TYPE: 415,
  UPLOAD_TOO_LARGE: 413,
  STORAGE_ERROR: 500,

  CONFIGURATION_ERROR: 500,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
});
